language: python
python:
  - "3.7"

# directories:
#  - "/tmp/texlive"
#  - "$HOME/.texlive"

before_install:
  - sudo apt-get -y install libgeos-dev
  - sudo apt-get -y install libproj-dev
  # - travis_wait 45 bash ./utilities/travis_setup.sh
  # - export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"

install:
  - pip install .
  - |
    python -m install_texlive -p $HOME/texlive -t 2020 --collections='-acfghuDFG' \
    -i 'koma-script,babel,csquotes,placeins,enumitem,siunitx,xpatch,standalone,circuitikz,xstring,fontawesome5,mleftright,mhchem,tabulary,tabu,varwidth,lstaddons,tcolorbox,mwe,fira,firamath,firamath-otf,xits,threeparttable,environ,trimspaces,pgfopts,ncctools'
  # we need graphs from this document
  - export PATH=$HOME/texlive/2020/bin/x86_64-linux:$PATH
  - tlmgr install --with-doc tex-overview

script:
- python setup.py test