# This is a TOML document.

title = "Train configuration"

[mode]
batch_mode = false
telegram_logger = true

[paths]
data_path = "./build/"
model_path = "./build/test_model/test.model"
pre_model = "none"
norm_path = "none"

[general]
fourier = true
source_list = false
arch_name = "filter_deep"
loss_func = "mse"
num_epochs = 2
inspection = false

[hypers]
batch_size = 64
lr = 1e-3