# This is a TOML document.

title = "Train configuration"

[paths]
data_path = "./build/"
model_path = "./build/models/test.model"

[general]
fourier = true
arch_name = "filter_deep"

[hypers]
batch_size = 64