# This is a TOML document.

title = "Simulation configuration"

[paths]
out_path = "./build"
data_format = "h5"

[mnist]
simulate = false
resource = "../../resources/mnist.pkl.gz"

[gaussians]
simulate = true
pointsources = false
num_pointsources = 20
pointlike_gaussians = true
num_pointlike_gaussians = 20
extended_gaussians = true
num_components = [4, 10]


[image_options]
num_bundles = 1
bundle_size = 500
img_size = 63
noise = false
