# This is a TOML document.

title = "Train configuration"

[mode]
batch_mode = true
gpu = true

[paths]
data_path = "./example_data/"
model_path = "./build/example_model/example.model"
norm_path = "none"

[general]
fourier = true
source_list = false
arch_name = "filter_deep"

[eval]
visualize_prediction = true
visualize_source_reconstruction = false
num_images = 5