# This is a TOML document.

title = "Evaluation configuration"

[mode]
quiet = true
gpu = true

[paths]
data_path = "./example_data/"
model_path = "./build/example_model/example.model"
model_path_2 = "none"
norm_path = "none"

[general]
plot_format = "png"
fourier = true
amp_phase = true
source_list = false
arch_name = "filter_deep"
separate = false
arch_name_2 = "none"

[inspection]
visualize_prediction = true
visualize_source_reconstruction = true
visualize_dynamic_range = true
visualize_blobs = true
visualize_ms_ssim = true
num_images = 5

[eval]
evaluate_viewing_angle = true
evaluate_dynamic_range = true
evaluate_ms_ssim = true