# This is a TOML document.

title = "Train configuration"

[mode]
batch_mode = true
gpu = false
telegram_logger = false

[paths]
data_path = "./example_data/"
model_path = "./build/example_model/example.model"
pre_model = "none"
norm_path = "none"

[general]
fourier = true
source_list = false
arch_name = "filter_deep"
loss_func = "splitted_mse"
num_epochs = 5
inspection = false

[hypers]
batch_size = 100
lr = 1e-3

[param_scheduling]
use = true
lr_start = 1e-3
lr_max = 5e-3
lr_stop = 7e-4