# This is a TOML document.

title = "Train configuration"

[mode]
quiet = false
telegram_logger = false
gpu = true

[paths]
data_path = "./build/normal/"
model_path = "./build/filter_deep_amp/filter_deep_amp.model"
pre_model = "none"
norm_path = "none"

[general]
fourier = true
amp_phase = true
source_list = false
arch_name = "filter_deep_amp"
loss_func = "loss_amp"
num_epochs = 400
inspection = false

[hypers]
batch_size = 100
lr = 2e-3

[param_scheduling]
use = true
lr_start = 1e-1
lr_max = 5e-1
lr_stop = 1e0